language: java
jdk:
  - openjdk11
deploy:
  provider: heroku
  api_key:
    secure: EZvy+Y7/CglItkkoqmT0+Qz46PI7vGWF3A2bY1/1/H0PgsJYtkPoa0onqoVtsMl0Dvvos9NBTWCwjiWjHYwXHunwkY+iF7woiQ6HV0R78VjXeWyl1gJmfY0i9dCKqhDmi81rFOIkpodfx2Pn5GeKKZt/l46VPKN7c4lZtB0uR/isHtOwYxHLQzi1dqLorquvJEghOG995oMBkEdwUfO+4PHQ3aWGtGhpALzJ5cTkoEQdWR5N+VoiEZuKnDKMtmMMD44hLIvJn7s3XqOAa2y1TIn+ieqw++yFw80DOrV14J+eUvPIgwEI1oAEfbGc3K7qix66r2zO7V7pvaKSXXvkJVRQvvXqjXiJ3fR6uICrd/ROnJ2wjRZ6UxX4TJUc4dYjkvzc9OsLAnyn0fZtbmQkyZXSrjthjGkxX0pMmwt98NGIGhCggIC/tahVzolAlpe4DIljCUR71iZePJ4Jp9cmEQzQ9nebZf4gl9fpqd1Q0K8RjbxxAKVxMD8VDqrnoD6T+RjBUBMJojAd+7FlQrB2c3p1sr8bNoS47jxQYVTCldAS8p5Yoli2uVcdngb+1ro4CiuASZxL9GJ9aEhcHDqIb5BBXisKvdjz5HXqv9ZwpfD5WHnUSPvXVKI/crOiGAD8UDrl1jF9FSeRLYocaC2KHmyyB/zdT309gpoALgH4dLw=
  app: command-line-webapp
